espipe:
  elasticsearch:
    host: localhost
    port: 9200
    protocol: http
    # fields_mode: flatten[default], custom_in_one, all_in_one[not support yet]
    fields_mode: flatten

# improve fetch data from database performance
#spring.datasource.hikari.auto-commit: false
# save 50% of performance by set fetch-size to 100, default is 10, 100k is reduced 7s to 3.5s
spring.jdbc.template.fetch-size: 100

