spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2.console.enabled: true
  sql:
    init:
      mode: embedded
      platform: h2
      schema-locations: classpath:espipe/h2/schema.sql
      data-locations: classpath:espipe/h2/data.sql